
services:
  web:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: user
      DB_PASS: pass
    depends_on:
      - db
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
